### ISSUE TITLE
루트 urls.py 업데이트

### ISSUE THREAD

**Issue by escape1001** [orm-final-101/dalim_api#2]
- swagger url패턴 붙이기
- 각 앱으로 include해서 보내주기
- media, statics url패턴 넣어주고 폴더 잡아주기

**Comment by escape1001** [comment]
@jiminkyung media폴더 같은 경우에는 gitignore 되어있어서 굳이 repo에는 만들지 않아도 될듯해요~

**Comment by jiminkyung** [comment]
@escape1001 @refelim @northeast23 넵 다들 pull 받으시고 .env파일, media폴더 생성해주시면 됩니다
